name: Deploy Review Page

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Build review content
      run: |
        # Create a simple static site with current content
        mkdir -p dist
        cat > dist/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Covexa - Content Review</title>
            <style>
                body { font-family: system-ui, sans-serif; max-width: 800px; margin: 0 auto; padding: 2rem; line-height: 1.6; }
                h1 { color: #2563eb; }
                h2 { color: #1f2937; border-bottom: 2px solid #e5e7eb; padding-bottom: 0.5rem; }
                .agent { background: #f8fafc; padding: 1rem; margin: 0.5rem 0; border-left: 4px solid #2563eb; }
                .features { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; }
                .feature { background: #f1f5f9; padding: 1rem; border-radius: 8px; }
            </style>
        </head>
        <body>
            <h1>Covexa – The AI Agent System for Modern GTM</h1>
            
            <h2>Company Overview</h2>
            <p><strong>Description:</strong> Private, compliance-ready intelligent AI GTM execution layer that coordinates apps, agents, and actions across your entire revenue stack.</p>
            
            <p><strong>Value Proposition:</strong> Covexa is your GTM execution layer — unify messy data, accelerate campaign creation, and orchestrate AI-powered outreach that leverages real-time intent signals and works across the tools your team already uses.</p>

            <h2>AI Agents</h2>
            <div class="agent"><strong>ORRA</strong> - Orchestration & Revenue Operations</div>
            <div class="agent"><strong>MIRA</strong> - Market Intelligence & Research Automation</div>
            <div class="agent"><strong>VARA</strong> - Voice & Relationship Automation</div>
            <div class="agent"><strong>LIA</strong> - Lead Intelligence & Analytics</div>
            <div class="agent"><strong>LEXA</strong> - Lead Extraction & Automation</div>
            <div class="agent"><strong>TORA</strong> - Task Orchestration & Routing Automation</div>
            <div class="agent"><strong>NIRA</strong> - Net Revenue Intelligence & Analytics</div>

            <h2>Core Features</h2>
            <div class="features">
                <div class="feature">AI-powered GTM execution</div>
                <div class="feature">CRM data unification</div>
                <div class="feature">Compliance-first automation</div>
                <div class="feature">Multi-agent orchestration</div>
                <div class="feature">Real-time intent signals</div>
                <div class="feature">Email automation</div>
                <div class="feature">Lead enrichment</div>
                <div class="feature">Revenue analytics</div>
            </div>

            <h2>Integrations</h2>
            <p>Slack, HubSpot, Gmail, ZoomInfo, Clearbit, Salesforce, 6sense, Bombora</p>

            <h2>Current Status</h2>
            <p><strong>Waitlist Phase:</strong> Join the Waitlist - Be the first to experience Covexa's AI-powered GTM platform</p>

            <h2>Target Use Cases</h2>
            <ul>
                <li>B2B sales teams needing automated outreach</li>
                <li>Revenue operations requiring data unification</li>
                <li>Marketing teams wanting intent-based campaigns</li>
                <li>Companies needing compliance-first automation</li>
            </ul>

            <p><em>Last updated: $(date)</em></p>
            <p><em>Auto-generated from Lovable project for GPT analysis</em></p>
        </body>
        </html>
        EOF
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist